[package]
name = "jokrey_utilities"
version = "0.1.2"
authors = ["jokrey <justin.bennett.developer@gmail.com>"]

[dependencies]
byteorder = "1"
time = "0.1"

[profile.dev]
opt-level = 0

[profile.release]
panic = 'abort'
opt-level = 3

[profile.test]
opt-level = 3